# Generated by Django 3.2.6 on 2022-03-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddmissionDetails',
            fields=[
                ('addmission_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('addmission_date', models.CharField(max_length=100)),
                ('addmission_year', models.CharField(max_length=100)),
                ('addmission_course', models.CharField(max_length=1000)),
                ('addmission_course_group', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'addmissionDetails',
            },
        ),
        migrations.CreateModel(
            name='FeesDetails',
            fields=[
                ('payment_date', models.CharField(max_length=10000)),
                ('total_amount', models.CharField(max_length=10000)),
                ('remaining_amount', models.CharField(max_length=10000)),
                ('payment_id', models.CharField(default='1', max_length=1000, primary_key=True, serialize=False)),
                ('addmission_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.addmissiondetails')),
            ],
            options={
                'db_table': 'feesDetails',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('userName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=1000)),
                ('salt', models.CharField(default='', max_length=1000)),
                ('position_college', models.CharField(default='False', max_length=1000)),
                ('position_hod', models.CharField(default='False', max_length=1000)),
                ('position_teacher', models.CharField(default='False', max_length=1000)),
                ('position_student', models.CharField(default='False', max_length=1000)),
                ('personality_form_check', models.CharField(default='False', max_length=1000)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='AcademicDetails.login')),
                ('college_name', models.CharField(max_length=1000)),
                ('college_principal_name', models.CharField(max_length=200)),
                ('college_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'college',
            },
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('hod_name', models.CharField(max_length=100)),
                ('hod_email', models.EmailField(max_length=254)),
                ('hod_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='AcademicDetails.login')),
                ('hod_departmentName', models.CharField(max_length=1000)),
                ('hod_image', models.CharField(max_length=10000, null=True)),
                ('college_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.college')),
            ],
            options={
                'db_table': 'hod',
            },
        ),
        migrations.CreateModel(
            name='TeachersDetails',
            fields=[
                ('teachers_name', models.CharField(max_length=100)),
                ('teachers_email', models.CharField(max_length=100)),
                ('teachers_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='AcademicDetails.login')),
                ('teachers_mobileNumber', models.CharField(max_length=1000)),
                ('teachers_groupName', models.CharField(max_length=1000)),
                ('image', models.CharField(blank=True, max_length=20000, null=True)),
                ('college_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.college')),
                ('hod_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.hod')),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('student_name', models.CharField(max_length=100)),
                ('student_registrationNumber', models.CharField(max_length=100)),
                ('student_email', models.CharField(max_length=100)),
                ('student_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='AcademicDetails.login')),
                ('student_permanentAddress', models.CharField(max_length=1000)),
                ('student_correspondenceAddress', models.CharField(max_length=1000)),
                ('student_adharcardNumber', models.CharField(max_length=1000)),
                ('student_mobileNumber', models.CharField(max_length=1000)),
                ('student_fatherMobileNumber', models.CharField(max_length=1000)),
                ('student_motherMobileNumber', models.CharField(max_length=1000)),
                ('student_dob', models.CharField(default='1899-09-09', max_length=1000)),
                ('student_gender', models.CharField(max_length=10)),
                ('student_marital_status', models.CharField(max_length=20)),
                ('student_bloodGroup', models.CharField(max_length=10)),
                ('student_category', models.CharField(max_length=100)),
                ('student_cast', models.CharField(max_length=1000)),
                ('student_alergy', models.CharField(max_length=1000)),
                ('student_familyDoctorName', models.CharField(max_length=1000)),
                ('student_familyDoctorNumber', models.CharField(max_length=1000)),
                ('student_familyDoctorAddress', models.CharField(max_length=1000)),
                ('student_healthProblem', models.CharField(max_length=1000)),
                ('student_regularMedicine', models.CharField(max_length=1000)),
                ('student_localGaurdianName', models.CharField(max_length=1000)),
                ('student_localGaurdianAddress', models.CharField(max_length=1000)),
                ('student_localGaurdianMobileNumber', models.CharField(max_length=1000)),
                ('student_localGaurdianEmail', models.CharField(max_length=1000)),
                ('student_previousCollegeName', models.CharField(max_length=1000)),
                ('student_additionalCourses', models.CharField(max_length=1000)),
                ('student_quetionNumber1Answer', models.CharField(max_length=1000)),
                ('student_quetionNumber2Answer', models.CharField(max_length=1000)),
                ('student_quetionNumber3Answer', models.CharField(max_length=1000)),
                ('student_quetionNumber4Answer', models.CharField(max_length=1000)),
                ('student_quetionNumber5Answer', models.CharField(max_length=1000)),
                ('image', models.CharField(max_length=100000, null=True)),
                ('college_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.college')),
                ('teachers_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.teachersdetails')),
            ],
            options={
                'db_table': 'studentDetails',
            },
        ),
        migrations.CreateModel(
            name='PreviousGTDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gt_year1', models.CharField(max_length=1000)),
                ('gt_year2', models.CharField(max_length=1000)),
                ('gt_year3', models.CharField(max_length=1000)),
                ('gt_year4', models.CharField(max_length=1000)),
                ('student_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.studentdetails')),
            ],
            options={
                'db_table': 'previousGTDetails',
            },
        ),
        migrations.CreateModel(
            name='FeesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_paid_date', models.CharField(max_length=10000)),
                ('previous_paid_amount', models.CharField(max_length=10000)),
                ('addmission_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.addmissiondetails')),
                ('payment_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.feesdetails')),
                ('student_id', models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.studentdetails')),
            ],
            options={
                'db_table': 'feesHistory',
            },
        ),
        migrations.AddField(
            model_name='feesdetails',
            name='student_id',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.studentdetails'),
        ),
        migrations.CreateModel(
            name='FamilyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatherName', models.CharField(max_length=1000)),
                ('motherName', models.CharField(max_length=1000)),
                ('brotherName', models.CharField(max_length=1000)),
                ('sisterName', models.CharField(max_length=1000)),
                ('spouseName', models.CharField(max_length=1000)),
                ('fatherOccupation', models.CharField(max_length=1000)),
                ('motherOccupation', models.CharField(max_length=1000)),
                ('spouseOccupation', models.CharField(max_length=1000)),
                ('fatherIncome', models.CharField(max_length=1000)),
                ('motherIncome', models.CharField(max_length=1000)),
                ('spouseIncome', models.CharField(max_length=1000)),
                ('student_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.studentdetails')),
            ],
            options={
                'db_table': 'familyDetails',
            },
        ),
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=1000)),
                ('present', models.CharField(max_length=10000000)),
                ('teachers_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.teachersdetails')),
            ],
            options={
                'db_table': 'attendence',
            },
        ),
        migrations.AddField(
            model_name='addmissiondetails',
            name='college_userName',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.college'),
        ),
        migrations.AddField(
            model_name='addmissiondetails',
            name='student_userName',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.studentdetails'),
        ),
        migrations.CreateModel(
            name='AcademicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_ssc', models.CharField(max_length=10000)),
                ('board_ssc', models.CharField(max_length=10000)),
                ('marks_ssc', models.CharField(max_length=10000)),
                ('year_passing_ssc', models.CharField(max_length=10000)),
                ('school_hsc', models.CharField(max_length=10000)),
                ('board_hsc', models.CharField(max_length=10000)),
                ('marks_hsc', models.CharField(max_length=10000)),
                ('year_passing_hsc', models.CharField(max_length=10000)),
                ('sem1_exam', models.CharField(max_length=10000)),
                ('sem1_result', models.CharField(max_length=10000)),
                ('sem1_percentage', models.CharField(max_length=10000)),
                ('sem1_subjectBack', models.CharField(max_length=10000)),
                ('sem2_exam', models.CharField(max_length=10000)),
                ('sem2_result', models.CharField(max_length=10000)),
                ('sem2_percentage', models.CharField(max_length=10000)),
                ('sem2_subjectBack', models.CharField(max_length=10000)),
                ('sem3_exam', models.CharField(max_length=10000)),
                ('sem3_result', models.CharField(max_length=10000)),
                ('sem3_percentage', models.CharField(max_length=10000)),
                ('sem3_subjectBack', models.CharField(max_length=10000)),
                ('sem4_exam', models.CharField(max_length=10000)),
                ('sem4_result', models.CharField(max_length=10000)),
                ('sem4_percentage', models.CharField(max_length=10000)),
                ('sem4_subjectBack', models.CharField(max_length=10000)),
                ('sem5_exam', models.CharField(max_length=10000)),
                ('sem5_result', models.CharField(max_length=10000)),
                ('sem5_percentage', models.CharField(max_length=10000)),
                ('sem5_subjectBack', models.CharField(max_length=10000)),
                ('sem6_exam', models.CharField(max_length=10000)),
                ('sem6_result', models.CharField(max_length=10000)),
                ('sem6_percentage', models.CharField(max_length=10000)),
                ('sem6_subjectBack', models.CharField(max_length=10000)),
                ('sem7_exam', models.CharField(max_length=10000)),
                ('sem7_result', models.CharField(max_length=10000)),
                ('sem7_percentage', models.CharField(max_length=10000)),
                ('sem7_subjectBack', models.CharField(max_length=10000)),
                ('sem8_exam', models.CharField(max_length=10000)),
                ('sem8_result', models.CharField(max_length=10000)),
                ('sem8_percentage', models.CharField(max_length=10000)),
                ('sem8_subjectBack', models.CharField(max_length=10000)),
                ('student_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.studentdetails')),
            ],
            options={
                'db_table': 'academicDetails',
            },
        ),
    ]
