# Generated by Django 3.2.6 on 2022-03-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicDetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feesdetails',
            old_name='student_id',
            new_name='student_userName',
        ),
        migrations.RenameField(
            model_name='feeshistory',
            old_name='student_id',
            new_name='student_userName',
        ),
        migrations.RenameField(
            model_name='previousgtdetails',
            old_name='student_id',
            new_name='student_userName',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='image',
            new_name='student_image',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='student_localGaurdianAddress',
            new_name='student_localGuardianAddress',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='student_localGaurdianEmail',
            new_name='student_localGuardianEmail',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='student_localGaurdianMobileNumber',
            new_name='student_localGuardianMobileNumber',
        ),
        migrations.RenameField(
            model_name='studentdetails',
            old_name='student_localGaurdianName',
            new_name='student_localGuardianName',
        ),
        migrations.RenameField(
            model_name='teachersdetails',
            old_name='image',
            new_name='teachers_image',
        ),
        migrations.RemoveField(
            model_name='teachersdetails',
            name='college_userName',
        ),
    ]
