# Generated by Django 3.2.6 on 2022-03-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicDetails', '0002_auto_20220326_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='college_email',
            field=models.CharField(max_length=1000),
        ),
    ]
