# Generated by Django 3.2.6 on 2022-03-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicDetails', '0003_alter_college_college_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_image',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
