# Generated by Django 3.2.6 on 2022-04-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicDetails', '0005_auto_20220401_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addmissiondetails',
            name='addmission_id',
            field=models.CharField(auto_created=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
