# Generated by Django 3.2.6 on 2022-04-01 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicDetails', '0006_alter_addmissiondetails_addmission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendence',
            name='present',
            field=models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.studentdetails'),
        ),
        migrations.AlterField(
            model_name='feesdetails',
            name='payment_id',
            field=models.CharField(auto_created=True, max_length=1000, primary_key=True, serialize=False),
        ),
    ]
