# Generated by Django 3.2.6 on 2022-04-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicDetails', '0008_auto_20220402_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previousgtdetails',
            old_name='gt_year1',
            new_name='gt_name',
        ),
        migrations.RenameField(
            model_name='previousgtdetails',
            old_name='gt_year2',
            new_name='year',
        ),
        migrations.RemoveField(
            model_name='previousgtdetails',
            name='gt_year3',
        ),
        migrations.RemoveField(
            model_name='previousgtdetails',
            name='gt_year4',
        ),
    ]
