# Generated by Django 3.2.6 on 2022-04-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicDetails', '0010_rename_year_passing_academicdetails_year_of_passing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeshistory',
            name='addmission_id',
        ),
        migrations.RemoveField(
            model_name='feeshistory',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='feeshistory',
            name='student_userName',
        ),
        migrations.DeleteModel(
            name='FeesDetails',
        ),
        migrations.DeleteModel(
            name='FeesHistory',
        ),
    ]
