# Generated by Django 3.2.6 on 2022-05-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicDetails', '0011_auto_20220410_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='student_fifthSet',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='student_firstSet',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='student_fourthSet',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='student_personalityAnalysis',
            field=models.CharField(default=1, max_length=10000),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='student_secondSet',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='student_thirdSet',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
