# Generated by Django 4.0.4 on 2022-05-05 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicDetails', '0012_auto_20220503_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_id', models.CharField(max_length=1000)),
                ('time', models.CharField(max_length=10000)),
                ('date', models.CharField(max_length=10000)),
                ('message', models.CharField(max_length=10000)),
                ('mom', models.CharField(max_length=100000, null=True)),
                ('status', models.CharField(max_length=500, null=True)),
                ('title', models.CharField(max_length=100000, null=True)),
                ('link', models.URLField(max_length=2000)),
                ('type_of_meeting', models.CharField(max_length=100000, null=True)),
                ('organiser_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='AcademicDetails.teachersdetails')),
            ],
            options={
                'db_table': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_of_appintment', models.CharField(max_length=1000)),
                ('date_of_appoinment', models.CharField(max_length=1000)),
                ('time_of_appoinment', models.CharField(max_length=1000)),
                ('approval_status', models.CharField(max_length=1000)),
                ('student_userName', models.ForeignKey(default='0', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.studentdetails')),
                ('teachers_userName', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='AcademicDetails.teachersdetails')),
            ],
            options={
                'db_table': 'appointmentDetails',
            },
        ),
    ]
