# Generated by Django 4.0.4 on 2022-05-12 10:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AcademicDetails', '0013_meeting_appointmentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hod',
            name='hod_email',
        ),
        migrations.AddField(
            model_name='hod',
            name='hod_mobileNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
